apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-demo-deployment
  labels:
    app: service-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-demo
  template:
    metadata:
      labels:
        app: service-demo
    spec:
      containers:
      - name: service-demo
        image: edunzz/service-demo:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-demo-01
spec:
  selector:
    app: service-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
